{{- if .Values.app.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "task-manager.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
  {{- with .Values.app.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if $.Values.app.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ $.Values.app.ingress.tls.issuer }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.app.ingress.className }}
  {{- if .Values.app.ingress.tls.enabled }}
  tls:
    {{- range .Values.app.ingress.hosts }}
    - hosts:
        - {{ .host | quote }}
      secretName: {{ $.Values.app.ingress.tls.secretName }}-{{ .host | replace "." "-" }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.app.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "task-manager.fullname" $ }}
                port:
                  number: 8080
          {{- end }}
    {{- end }}
{{- end }}