apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database password
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}