apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-manager.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-manager.selectorLabels" . | nindent 4 }}