---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: task-manager-dev
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/apps/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: operators
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: task-manager-dev
      namespace: flux-system
  timeout: 5m
  wait: true
