apiVersion: v2
name: task-manager
description: Task Manager REST API with PostgreSQL and Redis caching
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - task-manager
  - spring-boot
  - postgresql
  - redis
  - kubernetes
home: https://github.com/kingmetok/task-manager-k8s
sources:
  - https://github.com/kingmetok/task-manager-k8s
maintainers:
  - name: Misha
    email: your-email@example.com
icon: https://spring.io/images/spring-logo-9146a4d3298760c2e7e49595184e1975.svg